- name: Delete previous nginx.conf
  file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: Copy ubuntu ngix.conf file
  template:
    src: "{{ role_path }}/files/nginx-ubuntu.conf"
    dest: /etc/nginx/nginx.conf
    mode: 0644 
  when: ansible_distribution |lower == 'ubuntu'

- name: Copy centos ngix.conf file
  template:
    src: "{{ role_path }}/files/nginx-rhel.conf"
    dest: /etc/nginx/nginx.conf
    mode: 0644
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: Copy ssl config file
  template:
    src: "ssl.conf.j2"
    dest: "/etc/nginx/conf.d/ssl.conf"
    mode: 0644

- name: Configure nginx.service(always restart)
  shell: cp /lib/systemd/system/nginx.service tempservice && cat tempservice | sed -E 's/vice]/vice]\nRestart=always/' > /lib/systemd/system/nginx.service && rm tempservice
  become: true

- name: Reload systemctl daemon
  shell: systemctl daemon-reload
  become: true

- name: Enable nginx service
  service:
    name: nginx
    enabled: yes

- name: Restart nginx service
  service:
    name: nginx
    state: restarted