---
- name: install quorum
  debug:
      msg: "Installing Quorum"

- name: download quorum source code
  git:
      repo: "https://github.com/lacchain/quorum.git"
      dest: "/tmp/quorum"
      version: 94e1e31eb6a97e08dff4e44a8695dab1252ca3bc

- name: Building Quorum
  shell: ". /etc/profile.d/golang-vars.sh && make all "
  args:
      chdir: "/tmp/quorum"

- name: Copy Geth node to /usr/local/bin
  copy:
      src: /tmp/quorum/build/bin/geth
      dest: /usr/bin
      mode: 0755
      remote_src: yes

- name: Copy Boot node to /usr/local/bin
  copy:
      src: /tmp/quorum/build/bin/bootnode
      dest: /usr/bin
      mode: 0755
      remote_src: yes
